name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace
        run: pnpm build

      - name: Unit tests (Vitest)
        working-directory: apps/desktop
        run: pnpm test

      - name: Install Playwright browsers (Linux)
        if: runner.os == 'Linux'
        working-directory: apps/desktop
        run: pnpm exec playwright install --with-deps

      - name: Install Playwright browsers (macOS/Windows)
        if: runner.os != 'Linux'
        working-directory: apps/desktop
        run: pnpm exec playwright install

      - name: Run E2E tests
        working-directory: apps/desktop
        run: pnpm e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.os }}
          path: apps/desktop/playwright-report


